name: "Publish service image"
description: "Publishes a service Docker image to AWS"
inputs:
  ref:
    description: "The git reference (github.ref)"
    required: false
    default: ${{ github.ref }}
  sha:
    description: "The git sha from current commit"
    required: false
    default: ${{github.sha}}

runs:
  using: composite
  steps:
    - name: Publish Docker image
      run: |
        repository=528241396244.dkr.ecr.eu-central-1.amazonaws.com
        if [ "${{inputs.ref}}" == "refs/heads/master" ]
        then
          image_tag=${{env.PROJECT_VERSION}}
        else
          sha=${{inputs.sha}}
          short_commit_hash=${sha:0:7}
          image_tag=${{env.PROJECT_VERSION}}-dev-$short_commit_hash
        fi

        image_name="$repository/exhz/${PROJECT_NAME}:$image_tag"
        docker tag service $image_name
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $repository
        docker push $image_name
      shell: bash
